### ISSUE TITLE
Access point will not authenicate

### ISSUE THREAD

**Issue by geyseran** [mrtejas99/wifi-extender#1]
I have followed your instruction as decribed in github. I can see the new access point on wlan0 with its ip address and can also see an ip address on wlan1with dhcp ip fro my router. When I try to connect to the access point, the authentication fails. I have tried chaning the password, but still not success in connecting to the acccess point. I would appreaciate any help were possible?

**Comment by mrtejas99** [comment]
You can refer this section https://github.com/mrtejas99/wifi-extender#wlan0-as-ap. Also send me the contents of `/etc/wpa_supplicant/wpa_supplicant-wlan0.conf`

**Comment by geyseran** [comment]
I have reference the configuration as per your url. Here is my /etc/wpa_supplicant/wpa_supplicant-wlan0.conf:
country=ZA
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="RaspAP"
        mode=2
        key_mgmt=WPA-PSK
        psk="12345678#"
        frequency=2412
}

**Comment by mrtejas99** [comment]
Did you try connecting to **RaspAP** from any other device. Also, **forget** RaspAP and try reconnecting. One more thing, did you give read write permission and restarted wpa-supplicant?

**Comment by geyseran** [comment]
Thanks it seems that it was a permission issue on the conf file.
