### ISSUE TITLE
DNS hardcoded to 1.1.1.1

### ISSUE THREAD

**Issue by autarkper** [mrtejas99/wifi-extender#10]
It seems that the instructions and the setup script hardcode the DNS to go via 1.1.1.1 (Cloudflare).

/etc/systemd/network/08-wlan0.network:

```
[DHCPServer]
DNS=1.1.1.1
```

It think it would be better to hand the DNS requests to the router, which may know local addresses that Cloudflare does not know of.

**Comment by mrtejas99** [comment]
You can you whatever DNS you want. Feel free to change it
