### ISSUE TITLE
Is there a way to increase the security of the AP

### ISSUE THREAD

**Issue by bartenderck** [mrtejas99/wifi-extender#16]
Thank you for making this tutorial.  It has been an excellent use for my RPi Zero W.  Is there any way to increase the AP security from WPA to WPA2?  Thank you!

**Comment by mrtejas99** [comment]
yes, you can use WPA2. here is a reference to the [man page](https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf) 
TL;DR
`proto=RSN` implies  WPA2/IEEE 802.11i (also WPA2 can be used as an alias for RSN)

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country= IN

network={
        ssid="APtest"
        key_mgmt=WPA-PSK
        proto=RSN
        pairwise=CCMP
        group=CCMP
        psk="11111111"
}
```
