### ISSUE TITLE
Wifi channel

### ISSUE THREAD

**Issue by exp018** [mrtejas99/wifi-extender#2]
is there any way to change the wifi channel?

**Comment by mrtejas99** [comment]
Yes, you can use `iwconfig` to set the wifi channel.

First, install some dependencies
    
    sudo apt install wireless-regdb crda iw

Next, create a bash script, say `change_channel.sh` and add the following commands. The reason to make the script is that the setting will not be persistent after Pi reboots and will reset back to original.

    #!/bin/bash
    sudo iw reg set CA 
    sudo ifconfig wlan0 down
    sudo ifconfig wlan0 up
    sudo iwconfig wlan0 channel 7

*Replace the number `7` with the channel you want to replace with.*

Make the script executable
    
    sudo chmod +x /home/pi/wifi-extender/change_channel.sh

Now make sure that the script autostarts, You can use anything- `systemd`, `crontab` etc.
   
    crontab -e 
Then, add the line to load the script on every reboot.
   
    @reboot sh /home/pi/wifi-extender/change_channel.sh
Save the job and exit the editor ( for `vim`: press <kbd>Esc</kbd> and then <kbd>W</kbd><kbd>Q</kbd> , for `nano`: press <kbd>Ctrl</kbd><kbd>X</kbd>,<kbd>Y</kbd> and <kbd>Enter</kbd>
