### ISSUE TITLE
New Automatic script!

### ISSUE THREAD

**Issue by thewh1teagle** [mrtejas99/wifi-extender#3]
I found that the configurations steps are very grueling, So i decided to create a bash script that will config the whole stuffs automatically

I tested it on a fresh install of `Raspbian Lite` and it worked immediately after I ran the script!
That means you can create a wifi extender from your raspberry pi in something like 2 minutes and one command. 

[wifi_extender.bash](https://gist.github.com/thewh1teagle/c1b115894896986e5e5121d637fbc419)

**Comment by mrtejas99** [comment]
Great. Create a pull request for the script and I will add it to the repo. Thank you for your effort!

**Comment by thewh1teagle** [comment]
Hi!
I created pull request with the script and instructions for how to use it. 
https://github.com/mrtejas99/wifi-extender/pull/4
