### ISSUE TITLE
Isolated AP network

### ISSUE THREAD

**Issue by thewh1teagle** [mrtejas99/wifi-extender#5]
I would like to make the AP network of the raspberry pi fully isolated from the network which the internet comes from.
Does it's possible?

**Comment by mrtejas99** [comment]
I think it is possible. But you might have to check Raspberry Pi documentation. I have found the specific section [enable-routing-and-ip-masquerading](https://github.com/raspberrypi/documentation/blob/master/configuration/wireless/access-point-routed.md#enable-routing-and-ip-masquerading)
