### ISSUE TITLE
Not found interfaces

### ISSUE THREAD

**Issue by AlexMC** [mrtejas99/wifi-extender#6]
Hi, thanks for putting this together!

I tried to set up manually at first and then using the bash script and I'm getting this message, "Not Found Interfaces"

I'm using a rpi zero w with this wifi antenna: https://www.amazon.es/gp/product/B08HQJFB1G/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

This is the output:
<img width="637" alt="Screenshot 2021-04-25 at 10 42 39" src="https://user-images.githubusercontent.com/44814/115988955-c2bfa280-a5b3-11eb-826e-384289ac592e.png">

This is how I have everything connected:
![IMG_0847](https://user-images.githubusercontent.com/44814/115988995-ee428d00-a5b3-11eb-833d-2dc96c706e41.jpg)

What do you think is the issue? anything I can do to fix it?

**Comment by mrtejas99** [comment]
It looks like you have not installed the WiFi drivers for your card yet. Find out the name of our device so we can find the necessary drivers by running `lsusb`.

Let me know the output.
